# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jakob's KUB Summer Blog
# Description of the Site
description: A blog of what I did at my summer job at KUB
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: theawesomeboy360@gmail.com 
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  JT08397
youtube_channel_id: https://www.youtube.com/@Theawesomeboy360
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname:

# Name of the Author
author-name: Jakob Thurman
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/135718709?v=4
# 60 Words About the Author
author-about: My name is Jakob Thurman, and this blog chronicles my experiences at KUB. Given my passion for computers and editing, this job at KUB aligns perfectly with my interests. I aspire to attend college for video editing, as it would allow me to enhance my skills and potentially pursue it as a career. At the age of 17, I am currently in my final year of high school, and I have plans to enroll at UT once I complete my secondary education.
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
