# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jakob's KUB Summer Blog
# Description of the Site
description: A blog of what I did at my summer job at KUB
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: theawesomeboy360@gmail.com 
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  https://github.com/JT08397
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname:

# Name of the Author
author-name: Jakob Thurman
# URL for the Image of the Author
author-image: https://lh3.googleusercontent.com/DyBJz6LqJ0EPLmXkg4QA1rQ1IZ0UvqxF9pMgvUBiKaLqZE23ZiN57_E_85UrCz1ysYzYTn-5DORM1RYcIx00IBQcvQFWGlUwUO6GlEsKpX28LVrvhfTXryoBK9-FiMbDgiDRJ29uSLE_Xazuly2Syx1_qPolCYO8aA6n4JmF-SChA9XanyPbYinNUeDnmJTY7QG5XZqASwWAThiIj2aN3fBkH1LblCv1-bnOdE-sQJ3YunR_MfhA1WfHYT1_lV-0B725SiaAbAIY3U3O_5omr3-o021AEfuY8CvRPez5WIuAc-HfT-g7T-Z5OyYw-hAmkZGu6AxLptVaLy-xDyOWO36O1fhBEwqHuDA-UtN2Y7jTz8uwEa0sNSDjXoveeXvJQMCb5oUSmP8yJQfVIKyR6F1gLqOSHywx6CWzNKCPCtB0frucraWp94Dfrk1-rdC8CkpkXg39Ydpwyl3YTwIwj1n8GMp2v74efgkuDxmMOKCJWR6M-IuD4fDYE04ql53KwtKer_7tLG1i5b0YN_RfB8pgHzrxk1-6AHzDdz3dOa3r6wqo9Z-Oo_iQlHs1fA8pF8EePkwcDuZRIRyoh6Cup-0Sstz9-Xg5uIXwpDcVWaYlB6YipoJsfHKg2aAtS1ldO-TKUI81rQw6uWNZWo6lfSQMToF6leHfTxUSFRhEjVzluSmYdbh2VEY3aO74DyAALumCyEkhm5Jo32h5pzLy5adk-vP7KdERBrF9CnQ-8gKFSClpD59Ck2tESKvQOyWP1wjTIm1ogu4kagScnaYd5ZdyGDcRSKRHtr-RA3yHAyJWvMEbfCgsfiw-cGXy93FZzyyCyZoNGye5Q6-vZwCA9Los8dFQEe4vFMuCfisJNo311AIK_VNPyo7lZZJrL7vWQoPr-YIT9MqOKs6BDuqYxJ-h05JYAUWQqvFIBxPrkpQ4AA=w2800-h1863-s-no?authuser=0
# 60 Words About the Author
author-about: My name is Jakob thurman and this is a blog for my time at KUB. I have always loved computers and editing so this job at KUB fits for me. I want to go to college for video editing to improve my skills at it and maybe make it a job. Im 17 years old, Im on my last year of high school, and I plan to go to UT after school ends.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
